### ISSUE TITLE
toml config fails when uncommenting second dimension

### ISSUE THREAD

**Issue by SulpherStaer** [QuiltServerTools/TickTools#8]
The current config file presents itself as follows:
(I have altered a few settings, this is not default)

```toml
# Required options
splitTickDistance = true
# Required if relevant config option above is enabled
tickDistance = 8

[dynamic]
dynamicTickDistance = false
minTickDistance = 4
dynamicRenderDistance = true
minRenderDistance = 8
maxRenderDistance = 16

# Optional

itemDespawnTicks = 6000

# Example config for world specific
# Uncomment to use
#[the_nether]
    #splitTickDistance = true
    #tickDistance = 8
    #itemDespawnTicks = 6000

    #[dynamic]
    #   dynamicTickDistance = false
    #   minTickDistance = 4
    #   dynamicRenderDistance = false
    #   minRenderDistance = 4
    #   maxRenderDistance = 12
```

However, when uncommenting [the_nether] by just removing the hash marks, an error is given that the [dynamic] table is created twice.
[this online toml linter](https://www.toml-lint.com/) agrees that this is incorrect.

![image](https://user-images.githubusercontent.com/5037244/127561295-d53f88a2-3b8f-4235-be58-685ae1398e7d.png)

This error is server halting. The server refuses to boot due to the toml config file failure.

**Comment by Genau6502** [comment]
Dynamic table should be indented under the_nether table

**Comment by SulpherStaer** [comment]
I only removed the hashmarks. So it was indented. Unless I need to replace the hashmarks with spaces?

Still crashes.

**Comment by Genau6502** [comment]
I’ll leave this open then, will do more investigating

**Comment by Genau6502** [comment]
The dynamic table in a per-dimension override should be `<dimension_id_dynamic`. Please also check if #9 is fixed after this as well

**Comment by SulpherStaer** [comment]
Could you give an example for a normal fabric realm with no additional dimensions? I don't want to do it wrong, but I don't know what the id would be?

**Comment by KyGost** [comment]
@SulpherStaer
> Could you give an example for a normal fabric realm with no additional dimensions? I don't want to do it wrong, but I don't know what the id would be?

If by "normal fabric realm" I would imagine you mean no additional dimensions I would imagine:
```toml
# Required options
splitTickDistance = true
# Required if relevant config option above is enabled
tickDistance = 8

[dynamic]
dynamicTickDistance = false
minTickDistance = 4
dynamicRenderDistance = true
minRenderDistance = 8
maxRenderDistance = 16

# Optional

itemDespawnTicks = 6000

[the_nether]
    splitTickDistance = true
    tickDistance = 8
    itemDespawnTicks = 6000

    [the_nether_dynamic]
       dynamicTickDistance = false
       minTickDistance = 4
       dynamicRenderDistance = false
       minRenderDistance = 4
       maxRenderDistance = 12
```

---

Though this is kinda yuck, ideally there'd be a better TOML parser in play?
